//
//  SyzygyConditionals.h
//  Syzygy
//
//  Created by Dave DeLong on 4/16/18.
//  Copyright © 2018 Syzygy. All rights reserved.
//

// from http://sealiesoftware.com/blog/archive/2010/8/16/TargetConditionalsh.html

#define BUILDING_FOR_MAC (TARGET_OS_OSX)

#define BUILDING_FOR_ANY_IOS (TARGET_OS_IPHONE)
#define BUILDING_FOR_ANY_IOS_SIMULATOR (TARGET_OS_SIMULATOR)
#define BUILDING_FOR_ANY_IOS_DEVICE (TARGET_OS_EMBEDDED)

#define BUILDING_FOR_IOS (TARGET_OS_IOS)
#define BUILDING_FOR_IOS_DEVICE (BUILDING_FOR_IOS && BUILDING_FOR_ANY_IOS_DEVICE)
#define BUILDING_FOR_IOS_SIMULATOR (BUILDING_FOR_IOS && BUILDING_FOR_ANY_IOS_SIMULATOR)

#define BUILDING_FOR_WATCH (TARGET_OS_WATCH)
#define BUILDING_FOR_WATCH_DEVICE (BUILDING_FOR_WATCH && BUILDING_FOR_ANY_IOS_DEVICE)
#define BUILDING_FOR_WATCH_SIMULATOR (BUILDING_FOR_WATCH && BUILDING_FOR_ANY_IOS_SIMULATOR)

#define BUILDING_FOR_TV (TARGET_OS_TV)
#define BUILDING_FOR_TV_DEVICE (BUILDING_FOR_TV && BUILDING_FOR_ANY_IOS_DEVICE)
#define BUILDING_FOR_TV_SIMULATOR (BUILDING_FOR_TV && BUILDING_FOR_ANY_IOS_SIMULATOR)
